### ISSUE TITLE
Merge fail due to Permission denied

### ISSUE THREAD

**Issue by edouard-lopez** [wmanley/git-meld#15]
I checkout to upmc, then run : 
git meld master..upmc
Apply modifaction from master to upmc, try to save and got :
 Error writing to /tmp/git-meld.s1fLZw/upmc/flushTomcatCache.sh
 [Errno 13] Permission denied: '/tmp/git-meld.s1fLZw/upmc/flushTomcatCache.sh'.
Command line give this errors :
/usr/lib/meld/meld/meldwindow.py:572: Warning: g_object_set_qdata: assertion `G_IS_OBJECT (object)' failed
  self.notebook.append_page( page.widget, nbl)
/usr/lib/meld/meld/filediff.py:1005: Warning: g_object_set_qdata: assertion`G_IS_OBJECT (object)' failed
  msgarea.show_all()

**Comment by wmanley** [comment]
Try running

```
git meld master..
```

instead.  `git meld master..upmc` will compare the commit that master points at to the commit that upmc points at, this is not what you want to do in this instance.  You want to compare master to your current working directory.  git meld sets the files it creates in /tmp to be read-only because it isn't possible to directly edit the contents of a commit, you can only edit the contents of your working directory.  This helps to prevent losing work when the directories in /tmp are deleted.
