### ISSUE TITLE
if head is at current branch, don't copy it to tmpdir

### ISSUE THREAD

**Issue by kapouer** [wmanley/git-meld#2]
Hi,
if i do :
git checkout test
git meld master..test

it'd be nice the "test" branch not be copied in a tmp dir,
so that it's possible to actually copy stuff from master branch into test branch.

just an idea...

**Comment by wmanley** [comment]
If you don't specify a second revision it is implicitly your current working directory, which is modifiable.  So instead of `git meld master..test` you can do `git meld master..` or just `git meld master` which will allow you to copy things from your master branch into your working directory.  These changes can then become a commit on your test branch with `git commit -a`

Does this solve your problem or have I misunderstood?

**Comment by kapouer** [comment]
This does solve it, thank you.

**Comment by detly** [comment]
This doesn't seem to work with just eg. `git meld <some hash>..`.
